server:
  port: 30000
spring:
  application:
    name: dubbo_aaa
  redis:
    host: 1.13.253.101
    port: 6379
    password: 123456
    timeout: 5000
    lettuce:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 0
dubbo:
  scan:
    base-packages: com.dubbo.provider.service
  protocol:
    port: 30001
    name: dubbo
  registry:
    address: zookeeper://1.13.253.101:2181
  application:
    version: 1.0.0
