server:
  port: 30000
spring:
  application:
    name: dubbo_aaa
dubbo:
  scan:
    base-packages: com.dubbo.provider.service
  protocol:
    port: 30001
    name: dubbo
  registry:
    address: zookeeper://1.13.253.101:2181
  application:
    version: 1.0.0
