spring:
  kafka:
    bootstrap-servers: 192.168.242.131:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      compression-type: gzip #压缩算法
      acks: all #所有副本确认
      retries: 2 #重试次数
      properties:
        interceptor:
          classes: com.kfk.producer.interceptor.KmsgInterceptor
        enable:
          idempotence: true #幂等性
    consumer:
      group-id: boot-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
server:
  port: 24000